### PR TITLE
Upgrade to Kotlin 1.1.2

### PR DESCRIPTION
**Pull request by HughG**
I'm thinking of using Yested in a toy project, so I had a go at upgrading to the latest Kotlin, 1.1.2.

For now I've made the minimum changes needed to get the demo site to work for me.  I may make a sub-branch with "tidy-up" changes suggested by IntelliJ, including switching to using JQuery derived with ts2kt from DefinitelyTyped.

### CODE REVIEW

**Comment by Radisvoik** [comment]
You beat me to it!

**Comment by jean79** [comment]
Hi,
good job, Can you just remove Idea project files from the pull request?
.gitignore,
.Idea/*
Yested.iml
Thanks!
Jan

**Comment by HughG** [comment]
@Radisvoik, glad it may be of use to someone else :-)

**Comment by HughG** [comment]
@jean79, would it be okay to leave the IntelliJ files in the project? They shouldn't cause problems for anyone who doesn't use IntelliJ, and there are a couple of reasons I put them in, for me and any other IntelliJ users.

First, it means it's easy for me (and others) to click on build errors in the IntelliJ output window to jump to the problem.  If I run the build with IntelliJ's Maven UI, I get text output with errors but I can't click on them to jump to the problem.

Second, I also added docsite/docsite.iml as a "sub-project" for the demo site Kotlin files.  If I don't do that, IntelliJ doesn't build the demo site files, and doesn't find references from the demo site to the main Yested files.  I spend a while wondering why so many Yested classes and functions seemed to be unused, until I worked that out!

I can remove these things if you want, but it took me an hour or so to get the setup right.  Otherwise I'll have to leave them on my machine and try to remember not to commit them in future, and hope I don't accidentally delete them.

**Comment by HughG** [comment]
Hmm, actually ... I realise that with my IntelliJ changes I also needed to add the generated `docsite,js` to `index.html`.  I wasn't gong to check in that change since it's only because of my IntelliJ changes.  But then, looking at the `pom.xml`, I can't see how the demo site gets built into the generated `Yested.js` in the existing setup.  However, I don't really understand Maven -- I mainly use Gradle -- so maybe I'm missing something.

**Comment by Radisvoik** [comment]
@HughG @jean79   If my vote counts -- would be kind of nice having the project files there.

**Comment by jean79** [comment]
It might not work in different version of Intellij Idea. Can't we just refactor the maven project? So that it is not necessary to setup the project in Idea manually?

**Comment by HughG** [comment]
@jean79, that's a good point (about different IntelliJ versions).  I can try to refactor the Maven project but I don't really know Maven, so that may take me a while, unless you (or @Radisvoik) want to do it :-)

That would still leave me with the irritation that doing a Maven build doesn't let me easily jump to errors.  But maybe I just need to investigate the IntelliJ-Maven integration a bit more to get that working.  I know that, when IntelliJ imports from Gradle projects, you get clickable build output.

Actually, that's another option: I could probably convert your Maven project to Gradle, since I know it pretty well, and how it integrates with IntelliJ.  I'm definitely not trying to persuade you to do that, though: your project, your build system!  But I could if you like.

**Comment by HughG** [comment]
As a separate question, is there any Maven command to copy the JavaScript output of the main Yested library plus the demo site to the folder where the two need to be, for the demo site to run?  The page https://kotlinlang.org/docs/reference/using-maven.html mentions an `outputPath` attribute with no default, but I don't understand how that works.

**Comment by jean79** [comment]
Hi,
feel free to convert it to Gradle. I have no experience with Gradle so far.
Also would suggest you to check https://github.com/jean79/yested_fw/ . It
is a new version of Yested framework. This version is no longer maintained,
whereas Yested_FW has contributors.
Yested_FW has some nice features like bindable properties (aka JavaFX
bindable properties) and better utilize Kotlin HTML DSL.
Regards,
Jan

2017-06-06 22:05 GMT+02:00 HughG <notifications@github.com>:

**Comment by HughG** [comment]
Ah, heh, I wish I'd known that before I started looking at Yested.  Perhaps you or I should ping the JetBrains people to update the list at https://kotlinlang.org/docs/resources.html, since that's where I found it.  And/or, maybe you could update the link to the source on http://www.yested.net (in the "Get Yested" sidebar).

Would you and the other contributors be happy for me to move the new Yested to Gradle as well / instead?

**Comment by jean79** [comment]
My fault. I have raised a pull request to update the link on Kotlin pages.
I have also updated http://www.yested.net pages to refer to a new version.

I would like to keep the new Yested in Maven if you don't mind. We are
quite used to it.


2017-06-06 22:31 GMT+02:00 HughG <notifications@github.com>:

**Comment by HughG** [comment]
@jean79, I was tempted to try out gradle-script-kotlin but I've decided to just remove the IntelliJ stuff for now as you suggested, and go back to focusing on my original project.  I may yet try to upgrade the new Yested to 1.1.2, we'll see ...

**Pull request merged**
