### PR TITLE
Fix

### PR DESCRIPTION
**Pull request by bbodi**
some fixes

### CODE REVIEW

**Comment by jean79** [comment]
Hi, there seems to be some issue:
I got this:
```
Uncaught TypeError: Cannot read property 'name' of undefined
  Kotlin.defineRootPackage.bootstrap.Kotlin.definePackage.TagsSection.Kotlin.createClass.TagsSection$f_8	
  Kotlin.defineRootPackage.net.Kotlin.definePackage.yested.Kotlin.definePackage.bootstrap.Kotlin.definePackage.TagsInputField.Kotlin.createClass.init$f_3	
  m.event.dispatch	
  m.event.add.r.handle	
  m.event.trigger	
  (anonymous function)	
```

How is this tags supposed to work?

**Comment by bbodi** [comment]
I tried to reproduce it, but couldn't. Has it been solved then?

**Comment by jean79** [comment]
I have updated the demo site. I still occasionally get the error.
How should that tags work? I try to enter some text input input field but nothing happens.

**Comment by jean79** [comment]
Maybe I have included wrong Javascript library?
Can you check demo site?

**Comment by bbodi** [comment]
It works fine.
You can't add new elements here, because here I use objects (name and age pairs) instead of plain Strings. 
But you are right, I should add a demo where simpleStrings are used to illustrate this kind of mechanism too.

**Pull request merged**
